import React from 'react';
import './styles/css/globals.css';
import { StoreProvider } from '@/app/StoreProvider';
import { Header, Navbar, Footer } from '@/app/components/MainParts/index';
import PropTypes from 'prop-types';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={`antialiased`}>
          <Header />
          <Navbar />
          {children}
          <Footer />
        </body>
      </html>
    </StoreProvider>
  );
}

RootLayout.propTypes = {
  children: PropTypes.node.isRequired,
};
